#!/bin/bash

MAXVOL=300

if [ $# != 1 ]; then
    echo "Missing argument"
    echo "Usage: set_vol <vol>"
    exit 1
fi

Mute=$(pactl get-sink-mute @DEFAULT_SINK@)
if [ "$Mute" = "Mute: yes" ]; then
    pactl set-sink-mute @DEFAULT_SINK@ toggle
fi

pactl set-sink-volume @DEFAULT_SINK@ $1

Vol=$(pactl get-sink-volume @DEFAULT_SINK@ | head -n 1 | awk '{printf "%3d", $5}')
if [ $Vol -gt $MAXVOL ]; then
    pactl set-sink-volume @DEFAULT_SINK@ $MAXVOL%
fi
